Insert into cloth (category_Id, cloth_name, cloth_code, cloth_description, cloth_price, cloth_stock, cloth_size, cloth_color, cloth_material)
values 
(5, 'Men''s Suits', 'MS001', 'Used formal suit for men, available in various sizes', 3499.00, 20, 'L', 'Black', 'Linen'),
(6, 'Men''s T-Shirts', 'MTS001', 'Used T-shirts designed for men, in various styles and fits.', 89.00, 100, 'M', 'Blue', 'Cotton'),
(7, 'Men''s Jeans', 'MJN001', 'Used denim jeans made for men, including slim and regular fits.', 449.00, 50, '32', 'Dark Blue', 'Lightweight Denim'),
(8, 'Men''s Jackets', 'MJKT001', 'Used jackets designed for men, including leather and puffer styles.', 899.00, 30, 'M', 'Black', 'Cotton'),
(9, 'Men''s Sweaters', 'MSW001', 'Used sweaters made for men, in a variety of fabrics and styles.', 349.00, 60, 'L', 'Gray', 'Cotton Blend'),
(10, 'Men''s Shirts', 'MSS001', 'Used shirts designed for men, including dress shirts and casual button-downs.', 399.00, 40, 'L', 'White', 'Cotton'),
(11, 'Men''s Footwear', 'MFW001', 'Used shoes made for men, including sneakers, boots, and formal shoes.', 999.00, 25, '9', 'Brown', 'Leather'),
(12, 'Men''s Sportswear', 'MSP001', 'Used activewear for men, including athletic shorts, joggers, and jerseys.', 299.00, 80, 'M', 'Red', 'Polyester'),
(13, 'Men''s Belts', 'MSBT001', 'Used leather belts for men', 150.00, 40, 'Free Size', 'Brown', 'Leather'),
(13, 'Men''s Ties', 'MSTS001', 'Used silk ties for men, available in various patterns.', 200.00, 50, 'One Size', 'Red', 'Silk'),
(13, 'Men''s Caps', 'MSCP001', 'Used casual caps for men in various styles and colors.', 100.00, 60, 'One Size', 'Black', 'Cotton'),
(14, 'Women''s Sarees', 'WSRE001', 'Used traditional saree for women, available in cotton and silk.', 1500.00, 15, 'Free Size', 'Red', 'Cotton'),
(15, 'Women''s Salwar Kameez', 'WSK001', 'Used traditional three-piece outfit for women, including kameez, salwar, and dupatta.', 1700.00, 10, 'M', 'Blue', 'Cotton'),
(16, 'Women''s T-Shirts', 'WTS001', 'Used T-shirts designed for women, in a variety of styles and cuts.', 250.00, 70, 'S', 'Pink', 'Cotton'),
(17, 'Women''s Jeans', 'WJN001', 'Used denim jeans made for women, including skinny and bootcut fits.', 700.00, 50, '28', 'Light Blue', 'Lightweight Denim'),
(18, 'Women''s Jackets', 'WJKT001', 'Used jackets designed for women, including tailored blazers and parkas.', 1500.00, 30, 'M', 'Black', 'Cotton'),
(19, 'Women''s Sweaters', 'WSW001', 'Used sweaters made for women, including cardigans and pullovers.', 600.00, 60, 'S', 'Pink', 'Cotton Blend'),
(20, 'Women''s Shirts', 'WSS001', 'Used shirts designed for women, including blouses and tunics.', 800.00, 40, 'M', 'White', 'Cotton'),
(21, 'Women''s Footwear', 'WF001', 'Used shoes made for women, including heels, flats, and sandals.', 1000.00, 25, '8', 'Black', 'Leather'),
(22, 'Women''s Leggings', 'WLGN001', 'Used leggings for women, perfect for activewear.', 250.00, 80, 'M', 'Black', 'Polyester'),
(22, 'Women''s Sports Bras', 'WSB001', 'Used sports bras for women, ideal for athletic wear.', 150.00, 60, 'M', 'Pink', 'Nylon'),
(22, 'Women''s Tank Tops', 'WTTS001', 'Used tank tops for women, perfect for workout or casual wear.', 200.00, 100, 'M', 'White', 'Cotton'),
(23, 'Women''s Scarves', 'WSCV001', 'Used scarves for women, available in various fabrics and colors.', 150.00, 80, 'One Size', 'Beige', 'Silk'),
(23, 'Women''s Handbags', 'WHBS001', 'Used handbags for women, available in various styles.', 500.00, 40, 'One Size', 'Black', 'Leather'),
(23, 'Women''s Jewelry', 'WJWL001', 'Used jewelry for women, including bracelets, necklaces, and earrings.', 300.00, 50, 'One Size', 'Gold', 'Gold'),
(24, 'Oversized T-Shirts', 'OT001', 'Used trendy oversized t-shirt for unisex', 350.00, 100, 'M', 'White', 'Cotton'),
(25, 'Cargo Pants', 'CP001', 'Used unisex cargo pants with multiple pockets, perfect for casual streetwear.', 600.00, 50, 'M', 'Green', 'Cotton'),
(26, 'Denim Jackets', 'DJ001', 'Used classic and modern denim jackets suitable for everyone.', 1000.00, 60, 'L', 'Blue', 'Lightweight Denim'),
(27, 'Graphic Hoodies', 'GH001', 'Used stylish hoodies with bold graphics and streetwear designs.', 800.00, 70, 'M', 'Black', 'Cotton'),
(28, 'Joggers', 'JG001', 'Used comfortable unisex jogger pants for casual and athletic wear.', 400.00, 80, 'M', 'Gray', 'Polyester'),
(29, 'Varsity Jackets', 'VJ001', 'Used trendy varsity-style jackets inspired by college fashion.', 1200.00, 50, 'L', 'Red', 'Polyester'),
(30, 'Unisex Sneakers', 'US001', 'Used stylish sneakers designed to match modern unisex fashion.', 1000.00, 60, '9', 'White', 'Leather'),
(31, 'Bucket Hats', 'BH001', 'Used trendy hats for casual streetwear style.', 300.00, 150, 'Free Size', 'Black', 'Cotton'),
(32, 'Kids Graphic T-Shirts', 'KGTS001', 'Used T-shirts with fun designs, cartoons, and characters for kids.', 109.00, 100, 'S', 'Yellow', 'Cotton'),
(33, 'Kids Button-Down Shirts', 'KBDS001', 'Used casual button-down shirts with fun patterns for kids.', 179.00, 80, 'S', 'Blue', 'Cotton'),
(34, 'Kids Denim Shorts', 'KDS001', 'Used stylish and comfortable denim shorts for kids.', 199.00, 120, 'M', 'Denim Blue', 'Lightweight Denim'),
(35, 'Kids Jogger Pants', 'KJP001', 'Used comfortable jogger pants for kids, ideal for play and outdoor activities.', 149.00, 150, 'M', 'Gray', 'Cotton'),
(36, 'Kids Leggings', 'KLGN001', 'Used soft and stretchy leggings with playful patterns for kids.', 129.00, 200, 'S', 'Pink', 'Cotton'),
(37, 'Kids Puffer Jackets', 'KPJ001', 'Used warm puffer jackets for kids, ideal for winter or chilly weather.', 599.00, 50, 'M', 'Blue', 'Polyester'),
(38, 'Kids Raincoats', 'KRC001', 'Used waterproof raincoats with fun prints and hoods for kids.', 349.00, 60, 'M', 'Yellow', 'Polyester'),
(39, 'Kids Sneakers', 'KSNK001', 'Used durable sneakers for kids, perfect for outdoor play or casual outings.', 499.00, 100, '5', 'Red', 'Rubber'),
(40, 'Kids Sunglasses', 'KSUN001', 'Used colorful sunglasses for kids that provide UV protection.', 59.00, 150, 'Free Size', 'Pink', 'Plastic'),
(41, 'Kids Beanies', 'KB001', 'Used warm beanies with fun patterns for kids.', 79.00, 180, 'Free Size', 'Green', 'Wool'),
(42, 'Kids Backpacks', 'KBP001', 'Used lightweight, fun backpacks for kids with playful designs.', 199.00, 100, 'Free Size', 'Pink', 'Nylon'),
(43, 'Kids Costumes', 'KC001', 'Used superhero costumes, princess dresses, or animal outfits for kids.', 299.00, 70, 'S', 'Various', 'Polyester');
